name: Publish on Github, Curseforge & Modrinth

on: [ workflow_dispatch ]

env:
  RELEASE_NAME: 0.2.4 for Minecraft 1.19-1.19.2
  VERSION: 0.2.4
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth/Github)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          github-tag: "mc1.19.2-${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"
          github-prerelease: true

          modrinth-id: HtGckJVc
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          curseforge-id: 693995
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: beta
          changelog-file: CHANGELOG.md
          files: build/libs/!(*-@(dev|sources|javadoc)).jar

          loaders: fabric
          game-versions: |
            1.19
            1.19.1
            1.19.2
          java: |
            17
            18
            19
